# Generated by Django 4.1.2 on 2022-11-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1_score', models.IntegerField(verbose_name='AQ-1')),
                ('a2_score', models.IntegerField(verbose_name='AQ-2')),
                ('a3_score', models.IntegerField(verbose_name='AQ-3')),
                ('a4_score', models.IntegerField(verbose_name='AQ-4')),
                ('a5_score', models.IntegerField(verbose_name='AQ-5')),
                ('a6_score', models.IntegerField(verbose_name='AQ-6')),
                ('a7_score', models.IntegerField(verbose_name='AQ-7')),
                ('a8_score', models.IntegerField(verbose_name='AQ-8')),
                ('a9_score', models.IntegerField(verbose_name='AQ-9')),
                ('a10_score', models.IntegerField(verbose_name='AQ-10')),
                ('result', models.IntegerField(verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Escala AQ-10 - Criança',
            },
        ),
    ]
