# Generated by Django 4.1.2 on 2022-11-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('gender', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1, verbose_name='Gênero')),
                ('used_app_before', models.BooleanField(blank=True, null=True, verbose_name='Utilizou aplicativo antes?')),
                ('austim', models.BooleanField(blank=True, null=True, verbose_name='Possui algum parente autista?')),
                ('class_asd', models.BooleanField(verbose_name='Class ASD')),
            ],
            options={
                'verbose_name': 'Pessoa',
            },
        ),
    ]
