# Generated by Django 4.1.2 on 2022-11-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jaundice',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nasceu com icterícia?'),
        ),
    ]
