# Generated by Django 4.1.2 on 2022-11-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_aqchild_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='class_asd',
            field=models.BooleanField(blank=True, null=True, verbose_name='Class ASD'),
        ),
    ]
